Try using /usr/local/bin/runarchipel as archipel-agent binary if 'which runarchipel' fails. Should fix #212

diff --git a/ArchipelAgent/archipel-agent/install/etc/init.d/archipel b/ArchipelAgent/archipel-agent/install/etc/init.d/archipel
--- a/ArchipelAgent/archipel-agent/install/etc/init.d/archipel
+++ b/ArchipelAgent/archipel-agent/install/etc/init.d/archipel
@@ -27,9 +27,19 @@
 ### END INIT INFO
 
 ARCHIPEL=`which runarchipel`
+if [ $? -eq 1 ]; then
+  ARCHIPEL=/usr/local/bin/runarchipel
+  if [ ! -e "$ARCHIPEL" ]; then
+    echo 'Archipel exe not found !'
+    exit 1
+  fi
+fi
+
 PROG=$(basename $ARCHIPEL)
 PROGNAME="Archipel"
 ARCHIPEL_CONF_FILE="/etc/archipel/archipel.conf"
+
+
 
 if [[ -d /var/lock/subsys ]]; then
     lockfile=/var/lock/subsys/archipel
